sylius_grid:
    grids:
        app_admin_banner_image:
            driver:
                name: doctrine/orm
                options:
                    class: App\Entity\BannerImage
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete