sylius_grid:
    grids: 
        app_admin_car:
            driver:
                name: doctrine/orm
                options:
                    class: App\Entity\Car
            fields:
                Name:
                    type: string
                Brand:
                    type: string
                Model:
                    type: string
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete 
    
            
