sylius_paypal_webhook:
    resource: "@SyliusPayPalPlugin/Resources/config/webhook_routing.yaml"


app_banner_image:
    resource: |
        alias: app.banner_image
        section: admin
        templates: "@SyliusAdmin\\Crud"
        grid: app_admin_banner_image
        redirect: index
    type: sylius.resource
    prefix: admin