sylius_paypal_webhook:
    resource: "@SyliusPayPalPlugin/Resources/config/webhook_routing.yaml"

app_car:
    resource: |
        alias: app.car
        section: admin
        templates: "@SyliusAdmin\\Crud"
        grid: app_admin_car
        redirect: index
    type: sylius.resource
    prefix: admin




